version: '3.8'

services:
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - db_storage:/var/lib/postgresql/data

  redis:
    hostname: redis
    restart: always
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      # The standard AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      # The location of the RabbitMQ server.  amqp is the protocol;
      # rabbitmq is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
    db_storage:
    redis_storage: